steps:
  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://github.com/liquibase/liquibase/releases/download/v4.23.0/liquibase-4.23.0.tar.gz']
    dir: '/workspace'

  - name: 'gcr.io/cloud-builders/tar'
    args: ['tar -xzf', '/workspace/liquibase-4.23.0.tar.gz']
    dir: '/workspace'

  - name: 'liquibase/liquibase:latest'
    args: ['--driver=org.postgresql.Driver', '--url=jdbc:postgresql://10.74.32.9:5432/postgres', '--username=postgres', '--password=Welcome@123', 'update']

timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY
