trigger:
  branches:
    include:
      - main  # Replace 'main' with the branch name you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'

variables:
  PGHOST: 'test-postgres-2.postgres.database.azure.com'
  PGUSER: 'admin123'
  PGPASSWORD: 'Welcome@123'
  PGDATABASE: 'postgres'

steps:
  - task: Maven@3
    displayName: 'Build project'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'

  - script: |
      # Set variables for liquibase
      export PGHOST=$(PGHOST)
      export PGUSER=$(PGUSER)
      export PGPASSWORD=$(PGPASSWORD)
      export PGDATABASE=$(PGDATABASE)
      
      # Execute liquibase
      liquibase --changeLogFile=db.changelog.xml \
                --url=jdbc:postgresql://$PGHOST:5432/$PGDATABASE \
                --username=$PGUSER \
                --password=$PGPASSWORD \
                update
    displayName: 'Run Liquibase Update'
