trigger:
  branches:
    include:
      - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  PGHOST: 'postgretestdb2.postgres.database.azure.com'
  PGUSER: 'pavan'
  PGPASSWORD: 'Test@123'
  PGDATABASE: 'postgres'

steps:
  - task: Maven@3
    displayName: 'Build project'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'

  - script: |
      # Execute liquibase
      liquibase --changeLogFile=db.changelog.xml \
                --url=jdbc:postgresql://postgresql-name:5432/database-name \
                --username=$(PGUSER) \
                --password=$(PGPASSWORD) \
                update
    displayName: 'Run Liquibase Update'
